module ExaltedSite

import ExaltedLang.*

@if(ModuleExists("BrowserExtension.System"))
import BrowserExtension.DataStructures.*
@if(ModuleExists("BrowserExtension.System"))
import BrowserExtension.Classes.*
@if(ModuleExists("BrowserExtension.System"))
import BrowserExtension.System.*

// ============================================================================
//  EXALTED Terminal 77 — multi-language in-game browser Bible site.
//  Requires Cyberpunk 2077 Browser Extension Framework (Nexus mod 10038).
//
//  Scripture + UI strings are generated by scripts/langify.py (never edit the
//  generated data/ tree). Every route dispatches through the ExaltedLang
//  dispatcher with a language taken from the NETdir address, e.g.
//      NETdir://exalted.terminal/es/b/Gen
//  A bare NETdir://exalted.terminal (no language segment) resolves to the
//  default language (index 0 = English), so the original address keeps working.
//  Language selection therefore persists in the address itself — there is no
//  separate stored setting to get out of sync.
// ============================================================================

@if(ModuleExists("BrowserExtension.System"))
public class ExaltedSiteListener extends BrowserEventsListener {

  private let EXAL_BOOKS_PER_PAGE: Int32 = 8;
  private let EXAL_CHAPS_PER_PAGE: Int32 = 10;
  private let EXAL_PAGE_MARGIN: Float = 60.0;
  private let EXAL_DEFAULT_LANG: Int32 = 0;

  // UI key indices — MUST match the "keys" order in translations/ui.json.
  // langify.py writes the same order into each ExaltedUi<Sfx> module.
  private let UI_BIBLE_NAME: Int32 = 0;
  private let UI_EDITION: Int32 = 1;
  private let UI_STATS_BOOK: Int32 = 2;
  private let UI_STATS_CHAPTER: Int32 = 3;
  private let UI_STATS_VERSE: Int32 = 4;
  private let UI_OPEN_LIBRARY: Int32 = 5;
  private let UI_RED_LEGEND: Int32 = 6;
  private let UI_ABOUT_LINK: Int32 = 7;
  private let UI_ABOUT_HDR: Int32 = 8;
  private let UI_RED_LETTER_LINE: Int32 = 9;
  private let UI_GEN_LINE: Int32 = 10;
  private let UI_HOME: Int32 = 11;
  private let UI_LIBRARY_HDR: Int32 = 12;
  private let UI_SELECT_BOOK: Int32 = 13;
  private let UI_SELECT_CHAPTER: Int32 = 14;
  private let UI_CHAPTER_PREFIX: Int32 = 15;
  private let UI_PAGE_PREFIX: Int32 = 16;
  private let UI_PAGE_OF: Int32 = 17;
  private let UI_PREV: Int32 = 18;
  private let UI_NEXT: Int32 = 19;
  private let UI_LANGUAGE_HDR: Int32 = 20;
  private let UI_SELECT_LANGUAGE: Int32 = 21;
  private let UI_LANGUAGE_CURRENT: Int32 = 22;

  public func Init(logic: ref<BrowserGameController>) {
    super.Init(logic);

    this.m_siteData.address   = s"NETdir://exalted.terminal";
    this.m_siteData.shortName = s"Exalted Terminal 77";
    this.m_siteData.iconAtlasPath = r"base\\gameplay\\gui\\world\\internet\\templates\\atlases\\icons_atlas.inkatlas";
    this.m_siteData.iconTexturePart = n"zetatech1";
  }

  // --------------------------------------------------------------------------
  //  Router
  // --------------------------------------------------------------------------

  public func GetWebPage(address: String) -> ref<inkCompoundWidget> {
    let canvas = new inkCanvas();

    let path: String;
    if StrBeginsWith(address, s"NETdir://exalted.terminal") {
      path = StrAfterFirst(address, s"NETdir://exalted.terminal");
    } else {
      path = s"";
    };

    // Pull an optional leading /<code> language segment off the address, then
    // route on what remains. The language is carried on every link we emit, so
    // it survives navigation without any stored state.
    let lang = this.EXAL_ResolveLang(path);
    let route = this.EXAL_StripLang(path);

    // /<lang>/about
    if Equals(route, s"/about") {
      this.EXAL_AboutPage(canvas, lang);
      return canvas;
    };

    // /<lang>/lang  — language picker
    if Equals(route, s"/lang") {
      this.EXAL_LanguagePage(canvas, lang);
      return canvas;
    };

    // /<lang>/b/<short> or /<lang>/b/<short>/<pg>
    if StrBeginsWith(route, s"/b/") {
      let arg = StrAfterFirst(route, s"/b/");
      let bookShort = this.EXAL_TakeFirstPath(arg);
      let pg = 0;
      let rest = StrAfterFirst(arg, bookShort);
      if StrBeginsWith(rest, s"/") {
        pg = StringToInt(StrAfterFirst(rest, s"/"), 0);
      };
      let bookId = this.EXAL_FindBook(lang, bookShort);
      if bookId > 0 {
        this.EXAL_BookChapters(canvas, lang, bookId, pg);
      } else {
        this.EXAL_HomePage(canvas, lang);
      };
      return canvas;
    };

    // /<lang>/r/<short>/<ch>:<vp>
    if StrBeginsWith(route, s"/r/") {
      let arg = StrAfterFirst(route, s"/r/");
      let bookShort = this.EXAL_TakeFirstPath(arg);
      let rest = StrAfterFirst(arg, bookShort);
      let chapter = 0;
      let vp = 0;
      if StrBeginsWith(rest, s"/") {
        let chStr = StrAfterFirst(rest, s"/");
        let colonIdx = StrFindFirst(chStr, s":");
        if colonIdx >= 0 {
          chapter = StringToInt(StrMid(chStr, 0, colonIdx), 0);
          vp = StringToInt(StrMid(chStr, colonIdx + 1, StrLen(chStr) - colonIdx - 1), 0);
        };
      };
      let bookId = this.EXAL_FindBook(lang, bookShort);
      if bookId > 0 && chapter > 0 {
        this.EXAL_Reader(canvas, lang, bookId, chapter, vp);
      } else {
        this.EXAL_HomePage(canvas, lang);
      };
      return canvas;
    };

    // /<lang>/books or /<lang>/books/<pg>
    if StrBeginsWith(route, s"/books") {
      let pg = 0;
      let arg = StrAfterFirst(route, s"/books");
      if StrBeginsWith(arg, s"/") {
        pg = StringToInt(StrAfterFirst(arg, s"/"), 0);
      };
      this.EXAL_BookList(canvas, lang, pg);
      return canvas;
    };

    // default: home
    this.EXAL_HomePage(canvas, lang);
    return canvas;
  }

  // --------------------------------------------------------------------------
  //  String helpers (only funcs present in local redscript mods)
  // --------------------------------------------------------------------------

  private func EXAL_TakeFirstPath(arg: String) -> String {
    let idx = StrFindFirst(arg, s"/");
    if idx >= 0 {
      return StrMid(arg, 0, idx);
    };
    return arg;
  }

  // The first path segment is a language code only when ExaltedLangOfCode maps
  // it back to the SAME code (OfCode returns 0 for unknown, and 0 is also
  // "en", so a bare index is not proof).
  private func EXAL_IsLangSeg(seg: String) -> Bool {
    if StrLen(seg) == 0 {
      return false;
    };
    let idx = ExaltedLangOfCode(seg);
    return Equals(ExaltedLangCode(idx), seg);
  }

  private func EXAL_ResolveLang(path: String) -> Int32 {
    if StrBeginsWith(path, s"/") {
      let seg = this.EXAL_TakeFirstPath(StrAfterFirst(path, s"/"));
      if this.EXAL_IsLangSeg(seg) {
        return ExaltedLangOfCode(seg);
      };
    };
    return this.EXAL_DEFAULT_LANG;
  }

  private func EXAL_StripLang(path: String) -> String {
    if StrBeginsWith(path, s"/") {
      let seg = this.EXAL_TakeFirstPath(StrAfterFirst(path, s"/"));
      if this.EXAL_IsLangSeg(seg) {
        return StrAfterFirst(path, s"/" + seg);
      };
    };
    return path;
  }

  private func EXAL_Base(lang: Int32) -> String {
    return s"NETdir://exalted.terminal/" + ExaltedLangCode(lang);
  }

  private func EXAL_S(lang: Int32, key: Int32) -> String {
    return ExaltedUiLangStr(lang, key);
  }

  private func EXAL_FindBook(lang: Int32, short: String) -> Int32 {
    let i: Int32 = 1;
    while i <= ExaltedLangBookTotal(lang) {
      if Equals(ExaltedLangBookShort(lang, i), short) {
        return i;
      };
      i += 1;
    };
    return 0;
  }

  private func EXAL_Split(s: String, sep: String) -> array<String> {
    let parts: array<String>;
    let rem: String = s;
    let idx: Int32 = StrFindFirst(rem, sep);
    while idx >= 0 {
      ArrayPush(parts, StrMid(rem, 0, idx));
      rem = StrMid(rem, idx + StrLen(sep), StrLen(rem) - idx - StrLen(sep));
      idx = StrFindFirst(rem, sep);
    };
    if StrLen(rem) > 0 {
      ArrayPush(parts, rem);
    };
    return parts;
  }

  // --------------------------------------------------------------------------
  //  Widget helpers
  // --------------------------------------------------------------------------

  private func EXAL_MainPanel(parent: ref<inkCompoundWidget>) -> ref<inkVerticalPanel> {
    let panel = new inkVerticalPanel();
    panel.SetAnchor(inkEAnchor.TopLeft);
    panel.SetAnchorPoint(0.0, 0.0);
    panel.SetHAlign(inkEHorizontalAlign.Center);
    panel.SetVAlign(inkEVerticalAlign.Top);
    panel.SetFitToContent(true);
    panel.SetMargin(new inkMargin(this.EXAL_PAGE_MARGIN, 80.0, this.EXAL_PAGE_MARGIN, 24.0));
    panel.SetChildMargin(new inkMargin(0.0, 8.0, 0.0, 8.0));
    panel.Reparent(parent);
    return panel;
  }

  private func EXAL_NewText(parent: ref<inkCompoundWidget>, text: String, size: Int32,
                           red: Bool, bold: Bool) -> ref<inkText> {
    let t = new inkText();
    t.SetText(text);
    t.SetFontFamily("base\\gameplay\\gui\\fonts\\raj\\raj.inkfontfamily");
    t.SetFontStyle(n"Regular");
    if bold {
      t.SetFontStyle(n"Bold");
    };
    t.SetFontSize(size);
    t.SetTintColor(new HDRColor(0.9019, 0.9294, 0.9529, 1.0));
    if red {
      t.SetTintColor(new HDRColor(1.0, 0.2941, 0.2941, 1.0));
    };
    t.SetFitToContent(true);
    t.Reparent(parent);
    return t;
  }

  private func EXAL_NewBody(parent: ref<inkCompoundWidget>, text: String, size: Int32,
                           red: Bool) -> ref<inkText> {
    let t = this.EXAL_NewText(parent, text, size, red, false);
    t.SetHAlign(inkEHorizontalAlign.Left);
    t.SetVAlign(inkEVerticalAlign.Top);
    t.SetAnchor(inkEAnchor.TopLeft);
    t.SetMargin(new inkMargin(40.0, 0.0, 0.0, 0.0));
    return t;
  }

  private func EXAL_Header(parent: ref<inkCompoundWidget>, text: String) -> Void {
    let t = this.EXAL_NewText(parent, text, 72, false, true);
    t.SetHAlign(inkEHorizontalAlign.Left);
    t.SetMargin(new inkMargin(0.0, 0.0, 0.0, 14.0));
  }

  private func EXAL_SubHeader(parent: ref<inkCompoundWidget>, text: String) -> Void {
    let t = this.EXAL_NewText(parent, text, 40, false, false);
    t.SetHAlign(inkEHorizontalAlign.Left);
    t.SetMargin(new inkMargin(0.0, 0.0, 0.0, 14.0));
  }

  // A clickable nav link. The widget name carries the destination address so
  // the shared click callback can route without extra userdata objects.
  private func EXAL_Link(parent: ref<inkCompoundWidget>, text: String, address: String, size: Int32) -> Void {
    let t = this.EXAL_NewText(parent, text, size, false, false);
    t.SetName(StringToName(address));
    t.SetHAlign(inkEHorizontalAlign.Center);
    t.SetInteractive(true);
    t.RegisterToCallback(n"OnHoverOver", this, n"EXAL_OnHover");
    t.RegisterToCallback(n"OnHoverOut", this, n"EXAL_OnHoverOut");
    t.RegisterToCallback(n"OnRelease", this, n"EXAL_OnLinkClicked");
  }

  private func EXAL_Divider(parent: ref<inkCompoundWidget>) -> Void {
    let div = new inkRectangle();
    div.SetSize(new Vector2(1500.0, 3.0));
    div.SetTintColor(new HDRColor(0.1882, 0.2117, 0.2352, 1.0));
    div.SetOpacity(0.8);
    div.SetHAlign(inkEHorizontalAlign.Center);
    div.Reparent(parent);
  }

  // The shared language link (every page offers a way back to the picker).
  private func EXAL_LanguageLink(parent: ref<inkCompoundWidget>, lang: Int32, size: Int32) -> Void {
    this.EXAL_Link(parent, this.EXAL_S(lang, this.UI_LANGUAGE_HDR), this.EXAL_Base(lang) + s"/lang", size);
  }

  // --------------------------------------------------------------------------
  //  Home page
  // --------------------------------------------------------------------------

  private func EXAL_HomePage(canvas: ref<inkCompoundWidget>, lang: Int32) -> Void {
    let panel = this.EXAL_MainPanel(canvas);

    this.EXAL_Header(panel, s"EXALTED TERMINAL 77");
    this.EXAL_SubHeader(panel, this.EXAL_S(lang, this.UI_BIBLE_NAME));
    this.EXAL_SubHeader(panel,
      this.EXAL_S(lang, this.UI_STATS_BOOK) + s" " + IntToString(ExaltedLangBookTotal(lang))
      + s" / " + this.EXAL_S(lang, this.UI_STATS_CHAPTER) + s" " + IntToString(ExaltedLangChapterTotal(lang))
      + s" / " + this.EXAL_S(lang, this.UI_STATS_VERSE) + s" " + IntToString(ExaltedLangVerseTotal(lang)));
    this.EXAL_Divider(panel);

    this.EXAL_Link(panel, this.EXAL_S(lang, this.UI_OPEN_LIBRARY), this.EXAL_Base(lang) + s"/books", 62);

    // Only claim red letters when this language actually has them.
    if ExaltedLangRedTotal(lang) > 0 {
      let footer = this.EXAL_NewText(panel, this.EXAL_S(lang, this.UI_RED_LEGEND), 45, false, false);
      footer.SetHAlign(inkEHorizontalAlign.Center);
    };

    this.EXAL_Link(panel, this.EXAL_S(lang, this.UI_ABOUT_LINK), this.EXAL_Base(lang) + s"/about", 45);

    let cur = this.EXAL_NewText(panel,
      this.EXAL_S(lang, this.UI_LANGUAGE_CURRENT) + s": " + ExaltedLangEndonym(lang), 40, false, false);
    cur.SetHAlign(inkEHorizontalAlign.Center);
    this.EXAL_LanguageLink(panel, lang, 45);
  }

  // --------------------------------------------------------------------------
  //  About page
  // --------------------------------------------------------------------------

  private func EXAL_AboutPage(canvas: ref<inkCompoundWidget>, lang: Int32) -> Void {
    let panel = this.EXAL_MainPanel(canvas);

    this.EXAL_Header(panel, this.EXAL_S(lang, this.UI_ABOUT_HDR));
    this.EXAL_Divider(panel);

    let l1 = this.EXAL_NewText(panel, s"EXALTED Terminal 77", 60, false, true);
    l1.SetHAlign(inkEHorizontalAlign.Center);
    let l2 = this.EXAL_NewText(panel, this.EXAL_S(lang, this.UI_EDITION), 48, false, false);
    l2.SetHAlign(inkEHorizontalAlign.Center);
    if ExaltedLangRedTotal(lang) > 0 {
      let l3 = this.EXAL_NewText(panel, this.EXAL_S(lang, this.UI_RED_LETTER_LINE), 48, false, false);
      l3.SetHAlign(inkEHorizontalAlign.Center);
    };
    let l4 = this.EXAL_NewText(panel, this.EXAL_S(lang, this.UI_GEN_LINE), 42, false, false);
    l4.SetHAlign(inkEHorizontalAlign.Center);

    this.EXAL_Divider(panel);
    this.EXAL_Link(panel, this.EXAL_S(lang, this.UI_HOME), this.EXAL_Base(lang), 55);
    this.EXAL_LanguageLink(panel, lang, 45);
  }

  // --------------------------------------------------------------------------
  //  Language picker
  // --------------------------------------------------------------------------

  private func EXAL_LanguagePage(canvas: ref<inkCompoundWidget>, lang: Int32) -> Void {
    let panel = this.EXAL_MainPanel(canvas);
    this.EXAL_Header(panel, this.EXAL_S(lang, this.UI_LANGUAGE_HDR));

    let sub = this.EXAL_NewText(panel, this.EXAL_S(lang, this.UI_SELECT_LANGUAGE), 50, false, false);
    sub.SetHAlign(inkEHorizontalAlign.Center);
    this.EXAL_Divider(panel);

    let n = ExaltedLangTotal();
    let i = 0;
    while i < n {
      let label = ExaltedLangEndonym(i) + s"  (" + ExaltedLangName(i) + s")";
      this.EXAL_Link(panel, label, this.EXAL_Base(i), 52);
      i += 1;
    };

    this.EXAL_Divider(panel);
    let cur = this.EXAL_NewText(panel,
      this.EXAL_S(lang, this.UI_LANGUAGE_CURRENT) + s": " + ExaltedLangEndonym(lang), 44, false, false);
    cur.SetHAlign(inkEHorizontalAlign.Center);
    this.EXAL_Link(panel, this.EXAL_S(lang, this.UI_HOME), this.EXAL_Base(lang), 46);
  }

  // --------------------------------------------------------------------------
  //  Book list (paginated, 8 per page)
  // --------------------------------------------------------------------------

  private func EXAL_BookList(canvas: ref<inkCompoundWidget>, lang: Int32, pg: Int32) -> Void {
    let total = ExaltedLangBookTotal(lang);
    let pages = (total + this.EXAL_BOOKS_PER_PAGE - 1) / this.EXAL_BOOKS_PER_PAGE;
    let cur = Clamp(pg, 0, pages - 1);

    let panel = this.EXAL_MainPanel(canvas);
    this.EXAL_Header(panel, this.EXAL_S(lang, this.UI_LIBRARY_HDR));

    let sub = this.EXAL_NewText(panel, this.EXAL_S(lang, this.UI_SELECT_BOOK), 50, false, false);
    sub.SetHAlign(inkEHorizontalAlign.Center);

    this.EXAL_Divider(panel);

    let start = cur * this.EXAL_BOOKS_PER_PAGE;
    let end = start + this.EXAL_BOOKS_PER_PAGE;
    if end > total {
      end = total;
    };
    let i = start;
    while i < end {
      this.EXAL_Link(panel, ExaltedLangBookName(lang, i + 1),
        this.EXAL_Base(lang) + s"/b/" + ExaltedLangBookShort(lang, i + 1), 52);
      i += 1;
    };

    this.EXAL_Divider(panel);

    if cur > 0 {
      this.EXAL_Link(panel, this.EXAL_S(lang, this.UI_PREV), this.EXAL_Base(lang) + s"/books/" + IntToString(cur - 1), 46);
    };
    if cur + 1 < pages {
      this.EXAL_Link(panel, this.EXAL_S(lang, this.UI_NEXT), this.EXAL_Base(lang) + s"/books/" + IntToString(cur + 1), 46);
    };

    this.EXAL_Link(panel, this.EXAL_S(lang, this.UI_HOME), this.EXAL_Base(lang), 46);
    this.EXAL_LanguageLink(panel, lang, 46);
  }

  // --------------------------------------------------------------------------
  //  Chapter list for a book (paginated, 10 per page)
  // --------------------------------------------------------------------------

  private func EXAL_BookChapters(canvas: ref<inkCompoundWidget>, lang: Int32, bookId: Int32, pg: Int32) -> Void {
    let total = ExaltedLangBookChapterCount(lang, bookId);
    let pages = (total + this.EXAL_CHAPS_PER_PAGE - 1) / this.EXAL_CHAPS_PER_PAGE;
    let cur = Clamp(pg, 0, pages - 1);

    let panel = this.EXAL_MainPanel(canvas);
    this.EXAL_Header(panel, ExaltedLangBookName(lang, bookId));

    let sub = this.EXAL_NewText(panel, this.EXAL_S(lang, this.UI_SELECT_CHAPTER), 50, false, false);
    sub.SetHAlign(inkEHorizontalAlign.Center);

    this.EXAL_Divider(panel);

    let start = cur * this.EXAL_CHAPS_PER_PAGE;
    let end = start + this.EXAL_CHAPS_PER_PAGE;
    if end > total {
      end = total;
    };
    let i = start;
    while i < end {
      let baseAddr = this.EXAL_Base(lang) + s"/r/" + ExaltedLangBookShort(lang, bookId) + s"/" + IntToString(i + 1) + s":0";
      this.EXAL_Link(panel, this.EXAL_S(lang, this.UI_CHAPTER_PREFIX) + IntToString(i + 1), baseAddr, 50);
      i += 1;
    };

    this.EXAL_Divider(panel);

    if cur > 0 {
      let prevAddr = this.EXAL_Base(lang) + s"/b/" + ExaltedLangBookShort(lang, bookId) + s"/" + IntToString(cur - 1);
      this.EXAL_Link(panel, this.EXAL_S(lang, this.UI_PREV), prevAddr, 44);
    };
    if cur + 1 < pages {
      let nextAddr = this.EXAL_Base(lang) + s"/b/" + ExaltedLangBookShort(lang, bookId) + s"/" + IntToString(cur + 1);
      this.EXAL_Link(panel, this.EXAL_S(lang, this.UI_NEXT), nextAddr, 44);
    };

    this.EXAL_Link(panel, this.EXAL_S(lang, this.UI_HOME), this.EXAL_Base(lang), 44);
    this.EXAL_LanguageLink(panel, lang, 44);
  }

  // --------------------------------------------------------------------------
  //  Reader (paginated verses, 10 lines per page)
  // --------------------------------------------------------------------------

  private func EXAL_RedLine(text: String) -> String {
    // strips a leading "{r}" and trailing "{/r}" wrapper
    if StrBeginsWith(text, s"{r}") {
      let inner = StrMid(text, 3, StrLen(text) - 7);
      return inner;
    };
    return text;
  }

  private func EXAL_VerseLines(body: String) -> Int32 {
    // each generated "{~}" line becomes exactly one display row (hard-cut by
    // the generator) — pagination stays deterministic
    let lines = this.EXAL_Split(body, s"{~}");
    let n: Int32 = 0;
    let idx: Int32 = 0;
    while idx < ArraySize(lines) {
      n += 1;
      idx += 1;
    };
    return n;
  }

  private func EXAL_Reader(canvas: ref<inkCompoundWidget>, lang: Int32, bookId: Int32, chapter: Int32, vp: Int32) -> Void {
    let chapterText = ExaltedLangChapterText(lang, bookId, chapter);
    let verses = this.EXAL_Split(chapterText, s"{|}");
    let totalVerses = ArraySize(verses); // alternating [vnum, body, vnum, body, ...]
    let maxVerses = totalVerses / 2;

    let linesPerPage: Int32 = 10;

    // greedy pack verses into pages by exact display-line count
    let pageStarts: array<Int32>;
    let curLines = 0;
    let vi = 0;
    while vi < maxVerses {
      let body: String = s"";
      if vi * 2 + 1 < totalVerses {
        body = verses[vi * 2 + 1];
      };
      let bodyLines = this.EXAL_VerseLines(body);
      let need = 1 + bodyLines; // verse number row + body rows
      if curLines + need > linesPerPage && curLines > 0 {
        ArrayPush(pageStarts, vi);
        curLines = need;
      } else {
        curLines += need;
      };
      vi += 1;
    };
    let pages = ArraySize(pageStarts) + 1;
    let cur = Clamp(vp, 0, pages - 1);

    // page boundaries: page 0 starts at verse 0; page i+1 starts at pageStarts[i]
    let verseStart = cur == 0 ? 0 : pageStarts[cur - 1];
    let verseEnd = cur + 1 < pages ? pageStarts[cur] : maxVerses;

    let panel = this.EXAL_MainPanel(canvas);

    let head = ExaltedLangBookName(lang, bookId) + s" " + IntToString(chapter);
    this.EXAL_Header(panel, head);

    let sub = this.EXAL_NewText(panel,
      this.EXAL_S(lang, this.UI_PAGE_PREFIX) + IntToString(cur + 1)
      + this.EXAL_S(lang, this.UI_PAGE_OF) + IntToString(pages), 48, false, false);
    sub.SetHAlign(inkEHorizontalAlign.Center);

    this.EXAL_Divider(panel);

    // render the verses on this page
    let vi2 = verseStart;
    while vi2 < verseEnd {
      let vnum = verses[vi2 * 2];
      let body = s"";
      if vi2 * 2 + 1 < ArraySize(verses) {
        body = verses[vi2 * 2 + 1];
      };

      // verse number in muted color
      let numText = this.EXAL_NewText(panel, vnum, 44, false, true);
      numText.SetTintColor(new HDRColor(0.5450, 0.5803, 0.6196, 1.0));

      // body lines, one display row per generated "{~}" line
      let lines = this.EXAL_Split(body, s"{~}");
      let li = 0;
      while li < ArraySize(lines) {
        let line = lines[li];
        let isRed = StrBeginsWith(line, s"{r}");
        let inner = this.EXAL_RedLine(line);
        let t = this.EXAL_NewBody(panel, inner, 46, isRed);
        li += 1;
      };

      vi2 += 1;
    };

    // footer (divider + chapter/page nav) pinned to the canvas bottom so the
    // bottom edge does NOT move between pages (content height varies per page)
    let foot = new inkVerticalPanel();
    foot.SetAnchor(inkEAnchor.BottomCenter);
    foot.SetAnchorPoint(new Vector2(0.5, 1.0));
    foot.SetHAlign(inkEHorizontalAlign.Center);
    foot.SetVAlign(inkEVerticalAlign.Bottom);
    foot.SetFitToContent(true);
    foot.SetMargin(new inkMargin(0.0, 0.0, 0.0, 40.0));
    foot.SetChildMargin(new inkMargin(0.0, 4.0, 0.0, 4.0));
    foot.Reparent(canvas);

    this.EXAL_Divider(foot);

    let nav = new inkHorizontalPanel();
    nav.SetHAlign(inkEHorizontalAlign.Center);
    nav.SetFitToContent(true);
    nav.SetChildMargin(new inkMargin(20.0, 0.0, 20.0, 0.0));
    nav.Reparent(foot);

    if cur > 0 {
      let prevAddr = this.EXAL_Base(lang) + s"/r/" + ExaltedLangBookShort(lang, bookId) + s"/" + IntToString(chapter) + s":" + IntToString(cur - 1);
      this.EXAL_Link(nav, s"<< Page", prevAddr, 44);
    };
    if cur + 1 < pages {
      let nextAddr = this.EXAL_Base(lang) + s"/r/" + ExaltedLangBookShort(lang, bookId) + s"/" + IntToString(chapter) + s":" + IntToString(cur + 1);
      this.EXAL_Link(nav, s"Page >>", nextAddr, 44);
    };

    if chapter > 1 {
      let chAddr = this.EXAL_Base(lang) + s"/r/" + ExaltedLangBookShort(lang, bookId) + s"/" + IntToString(chapter - 1) + s":0";
      this.EXAL_Link(nav, s"<< Ch", chAddr, 44);
    };
    if chapter < ExaltedLangBookChapterCount(lang, bookId) {
      let chAddr = this.EXAL_Base(lang) + s"/r/" + ExaltedLangBookShort(lang, bookId) + s"/" + IntToString(chapter + 1) + s":0";
      this.EXAL_Link(nav, s"Ch >>", chAddr, 44);
    };

    let bookAddr = this.EXAL_Base(lang) + s"/b/" + ExaltedLangBookShort(lang, bookId);
    this.EXAL_Link(nav, s"[ CHAPTERS ]", bookAddr, 44);
    this.EXAL_Link(nav, s"[ HOME ]", this.EXAL_Base(lang), 44);
  }

  // --------------------------------------------------------------------------
  //  Pointer callbacks
  // --------------------------------------------------------------------------

  protected cb func EXAL_OnHover(evt: ref<inkPointerEvent>) -> Bool {
    let w = evt.GetTarget() as inkText;
    if IsDefined(w) {
      w.SetTintColor(new HDRColor(0.9607, 0.6509, 0.1372, 1.0));
    };
    return false;
  }

  protected cb func EXAL_OnHoverOut(evt: ref<inkPointerEvent>) -> Bool {
    let w = evt.GetTarget() as inkText;
    if IsDefined(w) {
      w.SetTintColor(new HDRColor(0.9019, 0.9294, 0.9529, 1.0));
    };
    return false;
  }

  protected cb func EXAL_OnLinkClicked(evt: ref<inkPointerEvent>) -> Bool {
    if evt.IsAction(n"click") {
      let w = evt.GetTarget() as inkText;
      if IsDefined(w) {
        let addr = NameToString(w.GetName());
        if StrLen(addr) > 0 {
          this.m_deviceLogicController.LoadPageByAddress(addr);
        };
        evt.Consume();
      };
    };
    return false;
  }
}

// ============================================================================
//  Fallback when Browser Extension is NOT installed (keeps redscript compiling)
// ============================================================================

@if(!ModuleExists("BrowserExtension.System"))
public class ExaltedSiteListener {
  public func Init(logic: ref<BrowserGameController>) {}
  public func Uninit() {}
  public func GetWebPage(address: String) -> ref<inkCompoundWidget> { return null; }
}

// ============================================================================
//  Hook BrowserGameController to register the site listener
// ============================================================================

@addField(BrowserGameController)
private let m_exaltedSiteListener: ref<ExaltedSiteListener>;

@wrapMethod(BrowserGameController)
protected cb func OnInitialize() -> Bool {
  let result = wrappedMethod();

  this.m_exaltedSiteListener = new ExaltedSiteListener();
  this.m_exaltedSiteListener.Init(this);

  return result;
}

@wrapMethod(BrowserGameController)
protected cb func OnUninitialize() -> Bool {
  let result = wrappedMethod();

  if IsDefined(this.m_exaltedSiteListener) {
    this.m_exaltedSiteListener.Uninit();
  };
  this.m_exaltedSiteListener = null;

  return result;
}
