module ExaltedSite

import ExaltedData.*

@if(ModuleExists("BrowserExtension.System"))
import BrowserExtension.DataStructures.*
@if(ModuleExists("BrowserExtension.System"))
import BrowserExtension.Classes.*
@if(ModuleExists("BrowserExtension.System"))
import BrowserExtension.System.*

// ============================================================================
//  EXALTED Terminal 77 — in-game browser Bible site.
//  Requires Cyberpunk 2077 Browser Extension Framework (Nexus mod 10038).
//  Data text is generated by scripts/gen-exalted-reds.py (do not edit data).
// ============================================================================

// ============================================================================
//  Site listener
// ============================================================================

@if(ModuleExists("BrowserExtension.System"))
public class ExaltedSiteListener extends BrowserEventsListener {

  private let EXAL_BOOKS_PER_PAGE: Int32 = 8;
  private let EXAL_CHAPS_PER_PAGE: Int32 = 10;
  private let EXAL_PAGE_MARGIN: Float = 60.0;

  public func Init(logic: ref<BrowserGameController>) {
    super.Init(logic);

    this.m_siteData.address   = s"NETdir://exalted.terminal";
    this.m_siteData.shortName = s"Exalted Terminal 77";
    this.m_siteData.iconAtlasPath = r"base\\gameplay\\gui\\world\\internet\\templates\\atlases\\icons_atlas.inkatlas";
    this.m_siteData.iconTexturePart = n"zetatech1";
  }

  // --------------------------------------------------------------------------
  //  Router
  // --------------------------------------------------------------------------

  public func GetWebPage(address: String) -> ref<inkCompoundWidget> {
    let canvas = new inkCanvas();

    let path: String;
    if StrBeginsWith(address, s"NETdir://exalted.terminal") {
      path = StrAfterFirst(address, s"NETdir://exalted.terminal");
    } else {
      path = s"";
    };

    // /about
    if Equals(path, s"/about") {
      this.EXAL_AboutPage(canvas);
      return canvas;
    };

    // /b/<short> or /b/<short>/<pg>
    if StrBeginsWith(path, s"/b/") {
      let arg = StrAfterFirst(path, s"/b/");
      let bookShort = this.EXAL_TakeFirstPath(arg);
      let pg = 0;
      let rest = StrAfterFirst(arg, bookShort);
      if StrBeginsWith(rest, s"/") {
        pg = StringToInt(StrAfterFirst(rest, s"/"), 0);
      };
      let bookId = this.EXAL_FindBook(bookShort);
      if bookId > 0 {
        this.EXAL_BookChapters(canvas, bookId, pg);
      } else {
        this.EXAL_HomePage(canvas);
      };
      return canvas;
    };

    // /r/<short>/<ch>:<vp>
    if StrBeginsWith(path, s"/r/") {
      let arg = StrAfterFirst(path, s"/r/");
      let bookShort = this.EXAL_TakeFirstPath(arg);
      let rest = StrAfterFirst(arg, bookShort);
      let chapter = 0;
      let vp = 0;
      if StrBeginsWith(rest, s"/") {
        let chStr = StrAfterFirst(rest, s"/");
        let colonIdx = StrFindFirst(chStr, s":");
        if colonIdx >= 0 {
          chapter = StringToInt(StrMid(chStr, 0, colonIdx), 0);
          vp = StringToInt(StrMid(chStr, colonIdx + 1, StrLen(chStr) - colonIdx - 1), 0);
        };
      };
      let bookId = this.EXAL_FindBook(bookShort);
      if bookId > 0 && chapter > 0 {
        this.EXAL_Reader(canvas, bookId, chapter, vp);
      } else {
        this.EXAL_HomePage(canvas);
      };
      return canvas;
    };

    // /books/<pg>
    if StrBeginsWith(path, s"/books") {
      let pg = 0;
      let arg = StrAfterFirst(path, s"/books");
      if StrBeginsWith(arg, s"/") {
        pg = StringToInt(StrAfterFirst(arg, s"/"), 0);
      };
      this.EXAL_BookList(canvas, pg);
      return canvas;
    };

    // default: home
    this.EXAL_HomePage(canvas);
    return canvas;
  }

  // --------------------------------------------------------------------------
  //  String helpers (only funcs present in local redscript mods)
  // --------------------------------------------------------------------------

  private func EXAL_TakeFirstPath(arg: String) -> String {
    let idx = StrFindFirst(arg, s"/");
    if idx >= 0 {
      return StrMid(arg, 0, idx);
    };
    return arg;
  }

  private func EXAL_FindBook(short: String) -> Int32 {
    let i: Int32 = 1;
    while i <= ExaltedBookTotal() {
      if Equals(ExaltedBookShort(i), short) {
        return i;
      };
      i += 1;
    };
    return 0;
  }

  private func EXAL_Split(s: String, sep: String) -> array<String> {
    let parts: array<String>;
    let rem: String = s;
    let idx: Int32 = StrFindFirst(rem, sep);
    while idx >= 0 {
      ArrayPush(parts, StrMid(rem, 0, idx));
      rem = StrMid(rem, idx + StrLen(sep), StrLen(rem) - idx - StrLen(sep));
      idx = StrFindFirst(rem, sep);
    };
    if StrLen(rem) > 0 {
      ArrayPush(parts, rem);
    };
    return parts;
  }

  // --------------------------------------------------------------------------
  //  Widget helpers
  // --------------------------------------------------------------------------

  private func EXAL_MainPanel(parent: ref<inkCompoundWidget>) -> ref<inkVerticalPanel> {
    let panel = new inkVerticalPanel();
    panel.SetAnchor(inkEAnchor.TopLeft);
    panel.SetAnchorPoint(0.0, 0.0);
    panel.SetHAlign(inkEHorizontalAlign.Center);
    panel.SetVAlign(inkEVerticalAlign.Top);
    panel.SetFitToContent(true);
    panel.SetMargin(new inkMargin(this.EXAL_PAGE_MARGIN, 80.0, this.EXAL_PAGE_MARGIN, 24.0));
    panel.SetChildMargin(new inkMargin(0.0, 8.0, 0.0, 8.0));
    panel.Reparent(parent);
    return panel;
  }

  private func EXAL_NewText(parent: ref<inkCompoundWidget>, text: String, size: Int32,
                           red: Bool, bold: Bool) -> ref<inkText> {
    let t = new inkText();
    t.SetText(text);
    t.SetFontFamily("base\\gameplay\\gui\\fonts\\raj\\raj.inkfontfamily");
    t.SetFontStyle(n"Regular");
    if bold {
      t.SetFontStyle(n"Bold");
    };
    t.SetFontSize(size);
    t.SetTintColor(new HDRColor(0.9019, 0.9294, 0.9529, 1.0));
    if red {
      t.SetTintColor(new HDRColor(1.0, 0.2941, 0.2941, 1.0));
    };
    t.SetFitToContent(true);
    t.Reparent(parent);
    return t;
  }

  private func EXAL_NewBody(parent: ref<inkCompoundWidget>, text: String, size: Int32,
                           red: Bool) -> ref<inkText> {
    let t = this.EXAL_NewText(parent, text, size, red, false);
    t.SetHAlign(inkEHorizontalAlign.Left);
    t.SetVAlign(inkEVerticalAlign.Top);
    t.SetAnchor(inkEAnchor.TopLeft);
    t.SetMargin(new inkMargin(40.0, 0.0, 0.0, 0.0));
    return t;
  }

  private func EXAL_Header(parent: ref<inkCompoundWidget>, text: String) -> Void {
    let t = this.EXAL_NewText(parent, text, 72, false, true);
    t.SetHAlign(inkEHorizontalAlign.Left);
    t.SetMargin(new inkMargin(0.0, 0.0, 0.0, 14.0));
  }

  private func EXAL_SubHeader(parent: ref<inkCompoundWidget>, text: String) -> Void {
    let t = this.EXAL_NewText(parent, text, 40, false, false);
    t.SetHAlign(inkEHorizontalAlign.Left);
    t.SetMargin(new inkMargin(0.0, 0.0, 0.0, 14.0));
  }

  // A clickable nav link. The widget name carries the destination address so
  // the shared click callback can route without extra userdata objects.
  private func EXAL_Link(parent: ref<inkCompoundWidget>, text: String, address: String, size: Int32) -> Void {
    let t = this.EXAL_NewText(parent, text, size, false, false);
    t.SetName(StringToName(address));
    t.SetHAlign(inkEHorizontalAlign.Center);
    t.SetInteractive(true);
    t.RegisterToCallback(n"OnHoverOver", this, n"EXAL_OnHover");
    t.RegisterToCallback(n"OnHoverOut", this, n"EXAL_OnHoverOut");
    t.RegisterToCallback(n"OnRelease", this, n"EXAL_OnLinkClicked");
  }

  private func EXAL_Divider(parent: ref<inkCompoundWidget>) -> Void {
    let div = new inkRectangle();
    div.SetSize(new Vector2(1500.0, 3.0));
    div.SetTintColor(new HDRColor(0.1882, 0.2117, 0.2352, 1.0));
    div.SetOpacity(0.8);
    div.SetHAlign(inkEHorizontalAlign.Center);
    div.Reparent(parent);
  }

  // --------------------------------------------------------------------------
  //  Home page
  // --------------------------------------------------------------------------

  private func EXAL_HomePage(canvas: ref<inkCompoundWidget>) -> Void {
    let panel = this.EXAL_MainPanel(canvas);

    this.EXAL_Header(panel, s"EXALTED TERMINAL 77");
    this.EXAL_SubHeader(panel, s"The Holy Bible - King James Version");
    this.EXAL_SubHeader(panel, s"66 Books / 1189 Chapters / 31102 Verses");
    this.EXAL_Divider(panel);

    this.EXAL_Link(panel, s"[ OPEN LIBRARY ]", s"NETdir://exalted.terminal/books", 62);

    let footer = this.EXAL_NewText(panel, s"Words of Jesus are shown in red.", 45, false, false);
    footer.SetHAlign(inkEHorizontalAlign.Center);

    this.EXAL_Link(panel, s"about this site", s"NETdir://exalted.terminal/about", 45);
  }

  // --------------------------------------------------------------------------
  //  About page
  // --------------------------------------------------------------------------

  private func EXAL_AboutPage(canvas: ref<inkCompoundWidget>) -> Void {
    let panel = this.EXAL_MainPanel(canvas);

    this.EXAL_Header(panel, s"ABOUT");
    this.EXAL_Divider(panel);

    let l1 = this.EXAL_NewText(panel, s"EXALTED Terminal 77", 60, false, true);
    l1.SetHAlign(inkEHorizontalAlign.Center);
    let l2 = this.EXAL_NewText(panel, s"Public domain King James Version, 1769.", 48, false, false);
    l2.SetHAlign(inkEHorizontalAlign.Center);
    let l3 = this.EXAL_NewText(panel, s"Red letter text marks the words of Jesus.", 48, false, false);
    l3.SetHAlign(inkEHorizontalAlign.Center);
    let l4 = this.EXAL_NewText(panel, s"redscript data generated by EXALTED scripts.", 42, false, false);
    l4.SetHAlign(inkEHorizontalAlign.Center);

    this.EXAL_Divider(panel);
    this.EXAL_Link(panel, s"[ HOME ]", s"NETdir://exalted.terminal", 55);
  }

  // --------------------------------------------------------------------------
  //  Book list (paginated, 8 per page)
  // --------------------------------------------------------------------------

  private func EXAL_BookList(canvas: ref<inkCompoundWidget>, pg: Int32) -> Void {
    let total = ExaltedBookTotal();
    let pages = (total + this.EXAL_BOOKS_PER_PAGE - 1) / this.EXAL_BOOKS_PER_PAGE;
    let cur = Clamp(pg, 0, pages - 1);

    let panel = this.EXAL_MainPanel(canvas);
    this.EXAL_Header(panel, s"THE LIBRARY");

    let sub = this.EXAL_NewText(panel, s"Select a book", 50, false, false);
    sub.SetHAlign(inkEHorizontalAlign.Center);

    this.EXAL_Divider(panel);

    let start = cur * this.EXAL_BOOKS_PER_PAGE;
    let end = start + this.EXAL_BOOKS_PER_PAGE;
    if end > total {
      end = total;
    };
    let i = start;
    while i < end {
      this.EXAL_Link(panel, ExaltedBookName(i + 1), s"NETdir://exalted.terminal/b/" + ExaltedBookShort(i + 1), 52);
      i += 1;
    };

    this.EXAL_Divider(panel);

    if cur > 0 {
      this.EXAL_Link(panel, s"[ << PREV PAGE ]", s"NETdir://exalted.terminal/books/" + IntToString(cur - 1), 46);
    };
    if cur + 1 < pages {
      this.EXAL_Link(panel, s"[ NEXT PAGE >> ]", s"NETdir://exalted.terminal/books/" + IntToString(cur + 1), 46);
    };

    this.EXAL_Link(panel, s"[ HOME ]", s"NETdir://exalted.terminal", 46);
  }

  // --------------------------------------------------------------------------
  //  Chapter list for a book (paginated, 10 per page)
  // --------------------------------------------------------------------------

  private func EXAL_BookChapters(canvas: ref<inkCompoundWidget>, bookId: Int32, pg: Int32) -> Void {
    let total = ExaltedBookChapterCount(bookId);
    let pages = (total + this.EXAL_CHAPS_PER_PAGE - 1) / this.EXAL_CHAPS_PER_PAGE;
    let cur = Clamp(pg, 0, pages - 1);

    let panel = this.EXAL_MainPanel(canvas);
    this.EXAL_Header(panel, ExaltedBookName(bookId));

    let sub = this.EXAL_NewText(panel, s"Select a chapter", 50, false, false);
    sub.SetHAlign(inkEHorizontalAlign.Center);

    this.EXAL_Divider(panel);

    let start = cur * this.EXAL_CHAPS_PER_PAGE;
    let end = start + this.EXAL_CHAPS_PER_PAGE;
    if end > total {
      end = total;
    };
    let i = start;
    while i < end {
      let baseAddr = s"NETdir://exalted.terminal/r/" + ExaltedBookShort(bookId) + s"/" + IntToString(i + 1) + s":0";
      this.EXAL_Link(panel, s"Chapter " + IntToString(i + 1), baseAddr, 50);
      i += 1;
    };

    this.EXAL_Divider(panel);

    if cur > 0 {
      let prevAddr = s"NETdir://exalted.terminal/b/" + ExaltedBookShort(bookId) + s"/" + IntToString(cur - 1);
      this.EXAL_Link(panel, s"[ << PREV PAGE ]", prevAddr, 44);
    };
    if cur + 1 < pages {
      let nextAddr = s"NETdir://exalted.terminal/b/" + ExaltedBookShort(bookId) + s"/" + IntToString(cur + 1);
      this.EXAL_Link(panel, s"[ NEXT PAGE >> ]", nextAddr, 44);
    };

    this.EXAL_Link(panel, s"[ HOME ]", s"NETdir://exalted.terminal", 44);
  }

  // --------------------------------------------------------------------------
  //  Reader (paginated verses, 10 per page)
  // --------------------------------------------------------------------------

  private func EXAL_RedLine(text: String) -> String {
    // strips a leading "{r}" and trailing "{/r}" wrapper
    if StrBeginsWith(text, s"{r}") {
      let inner = StrMid(text, 3, StrLen(text) - 7);
      return inner;
    };
    return text;
  }

  private func EXAL_VerseLines(body: String) -> Int32 {
    // each generated "{~}" line becomes exactly one display row (hard-cut at
    // 76 chars by the generator) — pagination stays deterministic
    let lines = this.EXAL_Split(body, s"{~}");
    let n: Int32 = 0;
    let idx: Int32 = 0;
    while idx < ArraySize(lines) {
      n += 1;
      idx += 1;
    };
    return n;
  }

  private func EXAL_Reader(canvas: ref<inkCompoundWidget>, bookId: Int32, chapter: Int32, vp: Int32) -> Void {
    let chapterText = ExaltedChapterText(bookId, chapter);
    let verses = this.EXAL_Split(chapterText, s"{|}");
    let totalVerses = ArraySize(verses); // alternating [vnum, body, vnum, body, ...]
    let maxVerses = totalVerses / 2;

    let linesPerPage: Int32 = 10;

    // greedy pack verses into pages by exact display-line count
    let pageStarts: array<Int32>;
    let curLines = 0;
    let vi = 0;
    while vi < maxVerses {
      let body: String = s"";
      if vi * 2 + 1 < totalVerses {
        body = verses[vi * 2 + 1];
      };
      let bodyLines = this.EXAL_VerseLines(body);
      let need = 1 + bodyLines; // verse number row + body rows
      if curLines + need > linesPerPage && curLines > 0 {
        ArrayPush(pageStarts, vi);
        curLines = need;
      } else {
        curLines += need;
      };
      vi += 1;
    };
    let pages = ArraySize(pageStarts) + 1;
    let cur = Clamp(vp, 0, pages - 1);

    // page boundaries: page 0 starts at verse 0; page i+1 starts at pageStarts[i]
    let verseStart = cur == 0 ? 0 : pageStarts[cur - 1];
    let verseEnd = cur + 1 < pages ? pageStarts[cur] : maxVerses;

    let panel = this.EXAL_MainPanel(canvas);

    let head = ExaltedBookName(bookId) + s" " + IntToString(chapter);
    this.EXAL_Header(panel, head);

    let sub = this.EXAL_NewText(panel, s"Page " + IntToString(cur + 1) + s" of " + IntToString(pages), 48, false, false);
    sub.SetHAlign(inkEHorizontalAlign.Center);

    this.EXAL_Divider(panel);

    // render the verses on this page
    let vi2 = verseStart;
    while vi2 < verseEnd {
      let vnum = verses[vi2 * 2];
      let body = s"";
      if vi2 * 2 + 1 < ArraySize(verses) {
        body = verses[vi2 * 2 + 1];
      };

      // verse number in muted color
      let numText = this.EXAL_NewText(panel, vnum, 44, false, true);
      numText.SetTintColor(new HDRColor(0.5450, 0.5803, 0.6196, 1.0));

      // body lines, one display row per generated "{~}" line
      let lines = this.EXAL_Split(body, s"{~}");
      let li = 0;
      while li < ArraySize(lines) {
        let line = lines[li];
        let isRed = StrBeginsWith(line, s"{r}");
        let inner = this.EXAL_RedLine(line);
        let t = this.EXAL_NewBody(panel, inner, 46, isRed);
        li += 1;
      };

      vi2 += 1;
    };

    // footer (divider + chapter/page nav) pinned to the canvas bottom so the
    // bottom edge does NOT move between pages (content height varies per page)
    let foot = new inkVerticalPanel();
    foot.SetAnchor(inkEAnchor.BottomCenter);
    foot.SetAnchorPoint(new Vector2(0.5, 1.0));
    foot.SetHAlign(inkEHorizontalAlign.Center);
    foot.SetVAlign(inkEVerticalAlign.Bottom);
    foot.SetFitToContent(true);
    foot.SetMargin(new inkMargin(0.0, 0.0, 0.0, 40.0));
    foot.SetChildMargin(new inkMargin(0.0, 4.0, 0.0, 4.0));
    foot.Reparent(canvas);

    this.EXAL_Divider(foot);

    let nav = new inkHorizontalPanel();
    nav.SetHAlign(inkEHorizontalAlign.Center);
    nav.SetFitToContent(true);
    nav.SetChildMargin(new inkMargin(20.0, 0.0, 20.0, 0.0));
    nav.Reparent(foot);

    if cur > 0 {
      let prevAddr = s"NETdir://exalted.terminal/r/" + ExaltedBookShort(bookId) + s"/" + IntToString(chapter) + s":" + IntToString(cur - 1);
      this.EXAL_Link(nav, s"<< Page", prevAddr, 44);
    };
    if cur + 1 < pages {
      let nextAddr = s"NETdir://exalted.terminal/r/" + ExaltedBookShort(bookId) + s"/" + IntToString(chapter) + s":" + IntToString(cur + 1);
      this.EXAL_Link(nav, s"Page >>", nextAddr, 44);
    };

    if chapter > 1 {
      let chAddr = s"NETdir://exalted.terminal/r/" + ExaltedBookShort(bookId) + s"/" + IntToString(chapter - 1) + s":0";
      this.EXAL_Link(nav, s"<< Ch", chAddr, 44);
    };
    if chapter < ExaltedBookChapterCount(bookId) {
      let chAddr = s"NETdir://exalted.terminal/r/" + ExaltedBookShort(bookId) + s"/" + IntToString(chapter + 1) + s":0";
      this.EXAL_Link(nav, s"Ch >>", chAddr, 44);
    };

    let bookAddr = s"NETdir://exalted.terminal/b/" + ExaltedBookShort(bookId);
    this.EXAL_Link(nav, s"[ CHAPTERS ]", bookAddr, 44);
    this.EXAL_Link(nav, s"[ HOME ]", s"NETdir://exalted.terminal", 44);
  }

  // --------------------------------------------------------------------------
  //  Pointer callbacks
  // --------------------------------------------------------------------------

  protected cb func EXAL_OnHover(evt: ref<inkPointerEvent>) -> Bool {
    let w = evt.GetTarget() as inkText;
    if IsDefined(w) {
      w.SetTintColor(new HDRColor(0.9607, 0.6509, 0.1372, 1.0));
    };
    return false;
  }

  protected cb func EXAL_OnHoverOut(evt: ref<inkPointerEvent>) -> Bool {
    let w = evt.GetTarget() as inkText;
    if IsDefined(w) {
      w.SetTintColor(new HDRColor(0.9019, 0.9294, 0.9529, 1.0));
    };
    return false;
  }

  protected cb func EXAL_OnLinkClicked(evt: ref<inkPointerEvent>) -> Bool {
    if evt.IsAction(n"click") {
      let w = evt.GetTarget() as inkText;
      if IsDefined(w) {
        let addr = NameToString(w.GetName());
        if StrLen(addr) > 0 {
          this.m_deviceLogicController.LoadPageByAddress(addr);
        };
        evt.Consume();
      };
    };
    return false;
  }
}

// ============================================================================
//  Fallback when Browser Extension is NOT installed (keeps redscript compiling)
// ============================================================================

@if(!ModuleExists("BrowserExtension.System"))
public class ExaltedSiteListener {
  public func Init(logic: ref<BrowserGameController>) {}
  public func Uninit() {}
  public func GetWebPage(address: String) -> ref<inkCompoundWidget> { return null; }
}

// ============================================================================
//  Hook BrowserGameController to register the site listener
// ============================================================================

@addField(BrowserGameController)
private let m_exaltedSiteListener: ref<ExaltedSiteListener>;

@wrapMethod(BrowserGameController)
protected cb func OnInitialize() -> Bool {
  let result = wrappedMethod();

  this.m_exaltedSiteListener = new ExaltedSiteListener();
  this.m_exaltedSiteListener.Init(this);

  return result;
}

@wrapMethod(BrowserGameController)
protected cb func OnUninitialize() -> Bool {
  let result = wrappedMethod();

  if IsDefined(this.m_exaltedSiteListener) {
    this.m_exaltedSiteListener.Uninit();
  };
  this.m_exaltedSiteListener = null;

  return result;
}