// Generated by scripts/gen-exalted-reds.py — do not edit.
// 66 books, 1189 chapters, 31102 verses, 2028 red-letter verses.
module ExaltedData

import ExaltedBook01.*
import ExaltedBook02.*
import ExaltedBook03.*
import ExaltedBook04.*
import ExaltedBook05.*
import ExaltedBook06.*
import ExaltedBook07.*
import ExaltedBook08.*
import ExaltedBook09.*
import ExaltedBook10.*
import ExaltedBook11.*
import ExaltedBook12.*
import ExaltedBook13.*
import ExaltedBook14.*
import ExaltedBook15.*
import ExaltedBook16.*
import ExaltedBook17.*
import ExaltedBook18.*
import ExaltedBook19.*
import ExaltedBook20.*
import ExaltedBook21.*
import ExaltedBook22.*
import ExaltedBook23.*
import ExaltedBook24.*
import ExaltedBook25.*
import ExaltedBook26.*
import ExaltedBook27.*
import ExaltedBook28.*
import ExaltedBook29.*
import ExaltedBook30.*
import ExaltedBook31.*
import ExaltedBook32.*
import ExaltedBook33.*
import ExaltedBook34.*
import ExaltedBook35.*
import ExaltedBook36.*
import ExaltedBook37.*
import ExaltedBook38.*
import ExaltedBook39.*
import ExaltedBook40.*
import ExaltedBook41.*
import ExaltedBook42.*
import ExaltedBook43.*
import ExaltedBook44.*
import ExaltedBook45.*
import ExaltedBook46.*
import ExaltedBook47.*
import ExaltedBook48.*
import ExaltedBook49.*
import ExaltedBook50.*
import ExaltedBook51.*
import ExaltedBook52.*
import ExaltedBook53.*
import ExaltedBook54.*
import ExaltedBook55.*
import ExaltedBook56.*
import ExaltedBook57.*
import ExaltedBook58.*
import ExaltedBook59.*
import ExaltedBook60.*
import ExaltedBook61.*
import ExaltedBook62.*
import ExaltedBook63.*
import ExaltedBook64.*
import ExaltedBook65.*
import ExaltedBook66.*

public func ExaltedBookTotal() -> Int32 { return 66; }
public func ExaltedVerseTotal() -> Int32 { return 31102; }
public func ExaltedRedTotal() -> Int32 { return 2028; }

public func ExaltedChapterText(book: Int32, chapter: Int32) -> String {
  switch book {
    case 1: return ExaltedBook01Chapter(chapter);
    case 2: return ExaltedBook02Chapter(chapter);
    case 3: return ExaltedBook03Chapter(chapter);
    case 4: return ExaltedBook04Chapter(chapter);
    case 5: return ExaltedBook05Chapter(chapter);
    case 6: return ExaltedBook06Chapter(chapter);
    case 7: return ExaltedBook07Chapter(chapter);
    case 8: return ExaltedBook08Chapter(chapter);
    case 9: return ExaltedBook09Chapter(chapter);
    case 10: return ExaltedBook10Chapter(chapter);
    case 11: return ExaltedBook11Chapter(chapter);
    case 12: return ExaltedBook12Chapter(chapter);
    case 13: return ExaltedBook13Chapter(chapter);
    case 14: return ExaltedBook14Chapter(chapter);
    case 15: return ExaltedBook15Chapter(chapter);
    case 16: return ExaltedBook16Chapter(chapter);
    case 17: return ExaltedBook17Chapter(chapter);
    case 18: return ExaltedBook18Chapter(chapter);
    case 19: return ExaltedBook19Chapter(chapter);
    case 20: return ExaltedBook20Chapter(chapter);
    case 21: return ExaltedBook21Chapter(chapter);
    case 22: return ExaltedBook22Chapter(chapter);
    case 23: return ExaltedBook23Chapter(chapter);
    case 24: return ExaltedBook24Chapter(chapter);
    case 25: return ExaltedBook25Chapter(chapter);
    case 26: return ExaltedBook26Chapter(chapter);
    case 27: return ExaltedBook27Chapter(chapter);
    case 28: return ExaltedBook28Chapter(chapter);
    case 29: return ExaltedBook29Chapter(chapter);
    case 30: return ExaltedBook30Chapter(chapter);
    case 31: return ExaltedBook31Chapter(chapter);
    case 32: return ExaltedBook32Chapter(chapter);
    case 33: return ExaltedBook33Chapter(chapter);
    case 34: return ExaltedBook34Chapter(chapter);
    case 35: return ExaltedBook35Chapter(chapter);
    case 36: return ExaltedBook36Chapter(chapter);
    case 37: return ExaltedBook37Chapter(chapter);
    case 38: return ExaltedBook38Chapter(chapter);
    case 39: return ExaltedBook39Chapter(chapter);
    case 40: return ExaltedBook40Chapter(chapter);
    case 41: return ExaltedBook41Chapter(chapter);
    case 42: return ExaltedBook42Chapter(chapter);
    case 43: return ExaltedBook43Chapter(chapter);
    case 44: return ExaltedBook44Chapter(chapter);
    case 45: return ExaltedBook45Chapter(chapter);
    case 46: return ExaltedBook46Chapter(chapter);
    case 47: return ExaltedBook47Chapter(chapter);
    case 48: return ExaltedBook48Chapter(chapter);
    case 49: return ExaltedBook49Chapter(chapter);
    case 50: return ExaltedBook50Chapter(chapter);
    case 51: return ExaltedBook51Chapter(chapter);
    case 52: return ExaltedBook52Chapter(chapter);
    case 53: return ExaltedBook53Chapter(chapter);
    case 54: return ExaltedBook54Chapter(chapter);
    case 55: return ExaltedBook55Chapter(chapter);
    case 56: return ExaltedBook56Chapter(chapter);
    case 57: return ExaltedBook57Chapter(chapter);
    case 58: return ExaltedBook58Chapter(chapter);
    case 59: return ExaltedBook59Chapter(chapter);
    case 60: return ExaltedBook60Chapter(chapter);
    case 61: return ExaltedBook61Chapter(chapter);
    case 62: return ExaltedBook62Chapter(chapter);
    case 63: return ExaltedBook63Chapter(chapter);
    case 64: return ExaltedBook64Chapter(chapter);
    case 65: return ExaltedBook65Chapter(chapter);
    case 66: return ExaltedBook66Chapter(chapter);
    default: return s"";
  };
}

public func ExaltedBookName(book: Int32) -> String {
  switch book {
    case 1: return s"Genesis";
    case 2: return s"Exodus";
    case 3: return s"Leviticus";
    case 4: return s"Numbers";
    case 5: return s"Deuteronomy";
    case 6: return s"Joshua";
    case 7: return s"Judges";
    case 8: return s"Ruth";
    case 9: return s"1 Samuel";
    case 10: return s"2 Samuel";
    case 11: return s"1 Kings";
    case 12: return s"2 Kings";
    case 13: return s"1 Chronicles";
    case 14: return s"2 Chronicles";
    case 15: return s"Ezra";
    case 16: return s"Nehemiah";
    case 17: return s"Esther";
    case 18: return s"Job";
    case 19: return s"Psalms";
    case 20: return s"Proverbs";
    case 21: return s"Ecclesiastes";
    case 22: return s"Song of Solomon";
    case 23: return s"Isaiah";
    case 24: return s"Jeremiah";
    case 25: return s"Lamentations";
    case 26: return s"Ezekiel";
    case 27: return s"Daniel";
    case 28: return s"Hosea";
    case 29: return s"Joel";
    case 30: return s"Amos";
    case 31: return s"Obadiah";
    case 32: return s"Jonah";
    case 33: return s"Micah";
    case 34: return s"Nahum";
    case 35: return s"Habakkuk";
    case 36: return s"Zephaniah";
    case 37: return s"Haggai";
    case 38: return s"Zechariah";
    case 39: return s"Malachi";
    case 40: return s"Matthew";
    case 41: return s"Mark";
    case 42: return s"Luke";
    case 43: return s"John";
    case 44: return s"Acts";
    case 45: return s"Romans";
    case 46: return s"1 Corinthians";
    case 47: return s"2 Corinthians";
    case 48: return s"Galatians";
    case 49: return s"Ephesians";
    case 50: return s"Philippians";
    case 51: return s"Colossians";
    case 52: return s"1 Thessalonians";
    case 53: return s"2 Thessalonians";
    case 54: return s"1 Timothy";
    case 55: return s"2 Timothy";
    case 56: return s"Titus";
    case 57: return s"Philemon";
    case 58: return s"Hebrews";
    case 59: return s"James";
    case 60: return s"1 Peter";
    case 61: return s"2 Peter";
    case 62: return s"1 John";
    case 63: return s"2 John";
    case 64: return s"3 John";
    case 65: return s"Jude";
    case 66: return s"Revelation";
    default: return s"";
  };
}

public func ExaltedBookShort(book: Int32) -> String {
  switch book {
    case 1: return s"Gen";
    case 2: return s"Ex";
    case 3: return s"Lev";
    case 4: return s"Num";
    case 5: return s"Deut";
    case 6: return s"Josh";
    case 7: return s"Judg";
    case 8: return s"Ruth";
    case 9: return s"1Sam";
    case 10: return s"2Sam";
    case 11: return s"1Kgs";
    case 12: return s"2Kgs";
    case 13: return s"1Chr";
    case 14: return s"2Chr";
    case 15: return s"Ezra";
    case 16: return s"Neh";
    case 17: return s"Esth";
    case 18: return s"Job";
    case 19: return s"Ps";
    case 20: return s"Prov";
    case 21: return s"Eccl";
    case 22: return s"Song";
    case 23: return s"Isa";
    case 24: return s"Jer";
    case 25: return s"Lam";
    case 26: return s"Ezek";
    case 27: return s"Dan";
    case 28: return s"Hos";
    case 29: return s"Joel";
    case 30: return s"Amos";
    case 31: return s"Obad";
    case 32: return s"Jonah";
    case 33: return s"Mic";
    case 34: return s"Nah";
    case 35: return s"Hab";
    case 36: return s"Zeph";
    case 37: return s"Hag";
    case 38: return s"Zech";
    case 39: return s"Mal";
    case 40: return s"Matt";
    case 41: return s"Mark";
    case 42: return s"Luke";
    case 43: return s"John";
    case 44: return s"Acts";
    case 45: return s"Rom";
    case 46: return s"1Cor";
    case 47: return s"2Cor";
    case 48: return s"Gal";
    case 49: return s"Eph";
    case 50: return s"Phil";
    case 51: return s"Col";
    case 52: return s"1Thess";
    case 53: return s"2Thess";
    case 54: return s"1Tim";
    case 55: return s"2Tim";
    case 56: return s"Titus";
    case 57: return s"Philem";
    case 58: return s"Heb";
    case 59: return s"Jas";
    case 60: return s"1Pet";
    case 61: return s"2Pet";
    case 62: return s"1John";
    case 63: return s"2John";
    case 64: return s"3John";
    case 65: return s"Jude";
    case 66: return s"Rev";
    default: return s"";
  };
}

public func ExaltedBookChapterCount(book: Int32) -> Int32 {
  switch book {
    case 1: return 50;
    case 2: return 40;
    case 3: return 27;
    case 4: return 36;
    case 5: return 34;
    case 6: return 24;
    case 7: return 21;
    case 8: return 4;
    case 9: return 31;
    case 10: return 24;
    case 11: return 22;
    case 12: return 25;
    case 13: return 29;
    case 14: return 36;
    case 15: return 10;
    case 16: return 13;
    case 17: return 10;
    case 18: return 42;
    case 19: return 150;
    case 20: return 31;
    case 21: return 12;
    case 22: return 8;
    case 23: return 66;
    case 24: return 52;
    case 25: return 5;
    case 26: return 48;
    case 27: return 12;
    case 28: return 14;
    case 29: return 3;
    case 30: return 9;
    case 31: return 1;
    case 32: return 4;
    case 33: return 7;
    case 34: return 3;
    case 35: return 3;
    case 36: return 3;
    case 37: return 2;
    case 38: return 14;
    case 39: return 4;
    case 40: return 28;
    case 41: return 16;
    case 42: return 24;
    case 43: return 21;
    case 44: return 28;
    case 45: return 16;
    case 46: return 16;
    case 47: return 13;
    case 48: return 6;
    case 49: return 6;
    case 50: return 4;
    case 51: return 4;
    case 52: return 5;
    case 53: return 3;
    case 54: return 6;
    case 55: return 4;
    case 56: return 3;
    case 57: return 1;
    case 58: return 13;
    case 59: return 5;
    case 60: return 5;
    case 61: return 3;
    case 62: return 5;
    case 63: return 1;
    case 64: return 1;
    case 65: return 1;
    case 66: return 22;
    default: return 0;
  };
}
